server:
    port: 6789

spring:
    application:
        name: base
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            url: jdbc:mysql://122.51.145.185:3437/financial_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: 951210
            driver-class-name: com.mysql.cj.jdbc.Driver
            # 连接池配置 #
            initial-size: 5 # 连接池初始化连接数
            max-active: 20  # 最大活跃连接数
            min-idle: 5     # 最小活跃连接数
            max-wait: 60000 # 获取连接等待超时时间
            max-pool-prepared-statement-per-connection-size: 20
            validation-query: SELECT 1 FROM DUAL
            filter: stat, wall # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall用于防火墙
    redis:
        host: 122.51.145.185
        port: 6336
        password: 951210
        lettuce:
            pool:
                max-active: 100
                max-wait: PT10S
                max-idle: 30
                min-idle: 1
        timeout: PT10S

mybatis:
    mapper-locations: classpath:mapper/*.xml
mybatis-plus:
    configuration:
        jdbc-type-for-null: "null"

eureka:
    client:
        service-url:
            defaultZone: http://localhost:1210/eureka/
